/**
 * Deterministic synthetic certificate source for the EDUCA demo seed.
 *
 * This module seeds the source model only. It does not create a printable
 * certificate. The issued record is derived by the database from a canonical
 * enrollment, closed sessions, and P attendance rows.
 */

import { generateAttendance } from './attendance-generator'

/** Synthetic institutional issuer used only by the deterministic demo. */
export const DEMO_CERTIFICATE_EMITTER_ID = '00000000-0000-0000-0000-000000001701'

/** Synthetic activity whose sessions prove the demo certificate workload. */
export const DEMO_CERTIFICATE_ACTIVITY_ID = '00000000-0000-0000-0000-000000001702'

/** Enrollment selected for the explicit synthetic certificate demonstration. */
export const DEMO_CERTIFICATE_MATRICULA_ID = '00000000-0000-0000-0000-000000000401'

/** Immutable id used to derive the synthetic certificate verification code. */
export const DEMO_CERTIFICATE_ISSUANCE_ID = '00000000-0000-0000-0000-000000001703'

export interface CertificateGenerationOptions {
  /** Inclusive end of the canonical attendance window, as YYYY-MM-DD. */
  anchorDate: string
}

const sqlLiteral = (value: string): string => `'${value.replace(/'/g, "''")}'`

/** Emits synthetic certificate-source SQL after canonical attendance SQL. */
export function certificateSql(options: CertificateGenerationOptions): string {
  const generatedAttendance = generateAttendance({ anchorDate: options.anchorDate })
  const qualifyingSessionIds = new Set(
    generatedAttendance.frequencia
      .filter(frequency => frequency.matriculaId === DEMO_CERTIFICATE_MATRICULA_ID && frequency.statusPresenca === 'P')
      .map(frequency => frequency.aulaId)
  )
  const activitySessionIds = generatedAttendance.aulas
    .filter(session => qualifyingSessionIds.has(session.id))
    .map(session => session.id)

  if (activitySessionIds.length === 0) {
    throw new Error('DEMO_CERTIFICATE_SOURCE_EMPTY')
  }

  const activitySessionRows = activitySessionIds
    .map(sessionId => `(${sqlLiteral(DEMO_CERTIFICATE_ACTIVITY_ID)},${sqlLiteral(sessionId)})`)
    .join(',\n')
  const emittedAt = `${options.anchorDate} 16:00:00-03`

  return [
    '-- Generated by certificate-generator.ts (deterministic synthetic certificate source)',
    `-- anchorDate: ${options.anchorDate} | qualifying P sessions: ${activitySessionIds.length}`,
    `INSERT INTO certificado_emissores (id,escola_id,nome_institucional,identificador_institucional,created_at) VALUES`,
    `(${sqlLiteral(DEMO_CERTIFICATE_EMITTER_ID)},${sqlLiteral('00000000-0000-0000-0000-000000000001')},${sqlLiteral('Instituicao Emissora Sintetica EDUCA')},${sqlLiteral('SYNTHETIC-EMEF001-CERTIFICATE')},${sqlLiteral(emittedAt)});`,
    `INSERT INTO certificado_atividades (id,turma_id,tipo,nome,created_at) VALUES`,
    `(${sqlLiteral(DEMO_CERTIFICATE_ACTIVITY_ID)},${sqlLiteral('00000000-0000-0000-0000-000000000101')},${sqlLiteral('ATIVIDADE')},${sqlLiteral('Atividade Sintetica de Matematica')},${sqlLiteral(emittedAt)});`,
    `INSERT INTO certificado_atividade_sessoes (atividade_id,sessao_id) VALUES\n${activitySessionRows};`,
    `INSERT INTO certificados_emitidos (id,atividade_id,matricula_id,emissor_id,emitido_em,created_at) VALUES`,
    `(${sqlLiteral(DEMO_CERTIFICATE_ISSUANCE_ID)},${sqlLiteral(DEMO_CERTIFICATE_ACTIVITY_ID)},${sqlLiteral(DEMO_CERTIFICATE_MATRICULA_ID)},${sqlLiteral(DEMO_CERTIFICATE_EMITTER_ID)},${sqlLiteral(emittedAt)},${sqlLiteral(emittedAt)});`,
  ].join('\n')
}
